# Generated by Django 4.0.8 on 2022-12-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='chapters_endpoint',
            field=models.URLField(blank=True, max_length=2000, unique=True),
        ),
    ]
