# Generated by Django 4.0.8 on 2022-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_description_alter_manga_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
