# Generated by Django 4.0.8 on 2022-12-07 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_remove_chapter_name_chapter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga', to_field='route'),
        ),
    ]
