# Generated by Django 4.0.8 on 2022-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, max_length=1000),
        ),
    ]
