# Generated by Django 4.0.8 on 2022-12-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_chapter_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.FileField(blank=True, max_length=255, upload_to='posters/'),
        ),
    ]
