# Generated by Django 4.0.8 on 2022-12-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, max_length=1000, unique=True),
        ),
        migrations.CreateModel(
            name='ChapterPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(max_length=1000, null=True, upload_to='chapters/%Y/%m/%d')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_parts', to='manga.chapter', to_field='number')),
            ],
        ),
    ]
