# Generated by Django 4.0.8 on 2022-12-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_manga_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
