# Generated by Django 4.0.8 on 2022-12-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_chapter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.FileField(max_length=255, null=True, upload_to='posters/'),
        ),
    ]
