# Generated by Django 4.0.8 on 2022-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_rename_filename_chapterpart_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='endpoint',
            field=models.URLField(blank=True, max_length=2000, unique=True),
        ),
    ]
