# Generated by Django 4.0.8 on 2022-12-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_manga_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='poster',
            field=models.ImageField(max_length=255, null=True, upload_to='posters/'),
        ),
    ]
